name: Build test with maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Release only if last commit message contains keyword 'PUBLISH' [not case-sensitive]
    if: "contains(github.event.head_commit.message, 'PUBLISH')"
    strategy:
      matrix:
        java-version: ['11', '16', '17']
    steps:
      - name: Set up JDK 11, 16 y 17
      - uses: actions/checkout@v2

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version}}
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        working-directory: 'string-array-utils'
        run: |
          mvn \
          --batch-mode \
          clean test
