name: Build test with maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Release only if last commit message contains keyword 'PUBLISH' [not case-sensitive]
    if: "contains(github.event.head_commit.message, 'PUBLISH')"
    strategy:
      matrix:
        java-version: ['11', '16', '17']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11, 16 y 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version}}
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: |
          mvn \
          --batch-mode \
          clean test

  publish:
    needs: test
    name: Bump maven version, release on Github and Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USER_NAME
          server-password: MAVEN_PASSWORD

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install GPG secret key
        run: echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | gpg --batch --import

      - name: Get lastest version and update based on previous commits
        run: ./bump_version.sh

      - name: Publish to Maven Central
        run: |
          mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase-${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          -DskipTests \
          -Prelease \
          deploy
        env:
          MAVEN_USER_NAME: ${{ secrets.MAVEN_USER_NAME}}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD}}


