name: Build test with maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '12', '13', '14', '15']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven simple
        run: mvn -B test

