name: Build test with maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '16', '17']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11, 12, 16 y 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven simple
        run: mvn -B test

